export const QUEUES_CONFIG = {
    PROCESS_WORKFLOW_JOB_QUEUE_WORKER_CONCURRENCY: Number.isNaN(Number(process.env.PROCESS_WORKFLOW_JOB_QUEUE_WORKER_CONCURRENCY)) ? 1 : Number(process.env.PROCESS_WORKFLOW_JOB_QUEUE_WORKER_CONCURRENCY),
} as const;